name: "Aboutsip.com"
description: ""

domain: aboutsip.github.com
author: Jonas Borjesson
email: jonas@aboutsip.com
title: Aboutsip

url: "http://localhost:4000"

markdown: rdiscount
permalink: pretty
highlighter: pygments
